# Generated by Django 5.2.5 on 2025-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='last_play_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
