# Generated by Django 5.2.5 on 2025-11-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userstats_last_play_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'Estadística de usuario', 'verbose_name_plural': 'Estadísticas de usuarios'},
        ),
        migrations.AddField(
            model_name='userstats',
            name='games_played',
            field=models.IntegerField(default=0, verbose_name='Partidas jugadas'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_response_time',
            field=models.FloatField(default=0.0, verbose_name='Tiempo promedio de respuesta (s)'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='avg_score',
            field=models.IntegerField(default=0, verbose_name='Puntaje promedio'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='consecutive_days',
            field=models.IntegerField(default=0, verbose_name='Días consecutivos jugando'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_play_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última fecha jugada'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='max_streak',
            field=models.IntegerField(default=0, verbose_name='Racha máxima global'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Puntaje total'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
