# Generated by Django 5.2.5 on 2025-11-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userstats_options_userstats_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='avg_response_time',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='max_streak',
        ),
    ]
